stages:
  - test

# Ein super kleines Image (nur ca. 5MB), das garantiert sofort lädt
image: alpine:latest

test-job:
  stage: test
  script:
    - echo "Prüfe Internetverbindung im Runner..."
    - ping -c 3 google.com
    - echo "CI/CD Verbindung zu GitLab steht! ✅"
    - echo "Aktuelles Verzeichnis:"
    - ls -la