# Globales Image (wird genutzt, wenn im Job nichts anderes steht)
image: cypress/browsers:latest 

stages:
  - test
  - deploy

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/.cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - .cache/Cypress
    - node_modules

cypress-run:
  stage: test
  # Nutze hier ein Image, das sicher existiert (Node 20 + Browser)
  image: cypress/browsers:node-20.17.0-chrome-128.0.6613.119-ff-128.0.3-edge-128.0.2739.42-1
  script:
    - npm install
    - npx cypress run --browser chrome
  artifacts:
    when: always
    paths:
      - cypress/screenshots
      - cypress/reports
    expire_in: 1 week

pages:
  stage: deploy
  dependencies:
    - cypress-run
  script:
    - mkdir -p public # -p verhindert Fehler, falls Ordner schon da ist
    - cp -r cypress/reports/* public/
  artifacts:
    paths:
      - public
  only:
    - main