name: Cypress Tests
on: 
    push:
        branches: [ main ]
        # Die Pipeline startet NUR, wenn sich Dateien in diesen Pfaden ändern:
        paths:
            - 'cypress/**'
            - 'package.json'
            - '.github/workflows/cypress_tests.yml'

jobs:
  cypress-run:
    # Hier definieren wir die Matrix
    strategy:
      matrix:
        os: [ubuntu-latest]
        #os: [ubuntu-latest, windows-latest] #does not work as path format problem
    
    # Hier wird der jeweilige Wert aus der Matrix eingesetzt
    runs-on: ${{ matrix.os }}
    #runs-on: ubuntu-latest # GitHub stellt einen frischen Linux-Server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6 # Es gibt fertige "Actions"
        with:
          browser: chrome
          # Der Report wird automatisch erstellt, wenn du ihn in der package.json hast

      - name: Upload Screenshots (bei Fehlern)
        uses: actions/upload-artifact@v4
        if: failure() # Nur ausführen, wenn die Tests scheitern
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: always() # Auch hochladen, wenn Tests fehlschlagen!
        with:
          folder: cypress/reports # Der Ordner, den Cypress erstellt hat
          branch: gh-pages        # Der Ziel-Branch für die Webseite

      - name: Add Link to Summary
        run: |
          echo "## 📊 Test Report" >> $GITHUB_STEP_SUMMARY
          echo "Den interaktiven Report findest du hier: [Klick mich](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/)" >> $GITHUB_STEP_SUMMARY